name: Sync GitHub Issues to Jira

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create Jira Issue
      if: github.event.action == 'opened'
      uses: atlassian/gajira-create@v3
      with:
        project: ${{ secrets.JIRA_PROJECT_KEY }}
        issuetype: Task
        summary: ${{ github.event.issue.title }}
        description: |
          GitHub Issue: ${{ github.event.issue.html_url }}
          
          ${{ github.event.issue.body }}
        fields: |
          {
            "labels": ["github-sync"]
          }
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Update Jira Issue
      if: github.event.action == 'edited'
      uses: atlassian/gajira-edit@v3
      with:
        issue: ${{ github.event.issue.number }}
        summary: ${{ github.event.issue.title }}
        description: |
          GitHub Issue: ${{ github.event.issue.html_url }}
          
          ${{ github.event.issue.body }}
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Close Jira Issue
      if: github.event.action == 'closed'
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ github.event.issue.number }}
        transition: "Done"
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
